#instructions to create docker container from the docker image of the agent. 
FROM nginx
COPY /home/ Documents/testing/agent_name/Example_Payload_Type/index.html 
#add the path where it has to be copied. 
